name: CI - macOS

on: [push, pull_request]

env:
  # Customize the CMake build type here (Release, Debug, RelWithDebInfo, etc.)
  BUILD_TYPE: Debug

jobs:
  build:
    # The CMake configure and build commands are platform agnostic and should work equally well on Windows or Mac.
    # You can convert this to a matrix build if you need cross-platform coverage.
    # See: https://docs.github.com/en/free-pro-team@latest/actions/learn-github-actions/managing-complex-workflows#using-a-build-matrix
    runs-on: macos-latest

    steps:
    - uses: actions/checkout@v2
    
    - name: Install python  
      shell: bash
      run: |
            apt-get install mosquitto cmake python python-pip && python -m pip install conan
            pip install conan
    - name: Install dependencies with conan
      shell: bash
      run: |
            cd cmake
            conan install ../scripts
    - name: Build
      # Build your program with the given configuration    
      run: |
           mkdir build
           cd build
           cmake ..
    - name: Test
      working-directory: ${{github.workspace}}/build
      # Execute tests defined by the CMake configuration.  
      # See https://cmake.org/cmake/help/latest/manual/ctest.1.html for more detail
      run: ctest -C ${{env.BUILD_TYPE}}

      
